### PR TITLE
Add pipeline lightweight checkout support

### PR DESCRIPTION
**Pull request by mellena1**
I have a PR out of JJB, I'm waiting for that to be approved and merged. Once it is, we can merge this in whenever.

We can make the decision whether to wait for them to add it into a release version or merge when it gets added to a beta version...

### CODE REVIEW

**Comment by ktdreyer** [comment]
Sounds good. Want to put a link to your submission to JJB?

**Comment by mellena1** [comment]
Sure.

[https://review.openstack.org/#/c/555024/](https://review.openstack.org/#/c/555024/)

**Comment by frayedknot** [comment]
Thanks for this! Any idea on when this could hit both projects?

**Comment by ktdreyer** [comment]
From https://review.openstack.org/205637, 

> Hi Ken, at ONS last week we discussed with the OpenStack infra folks about changing the committers for this project as the current committers are not that active as of late. We got approval to promote new committers from the JJB team. I'm still travelling and won't be back until later this week but we plan to sort out the committers team and hopefully have some more active committers moving forward. Let me sync up with the new committers this week and see what we can do to get more activity in this project. Sorry for the long wait.


https://review.openstack.org/#/admin/groups/194,members has a few new people now.

**Comment by zxiiro** [comment]
Hi Folks,

I just pushed out a JJB 2.0.5 so should appear in pypi shortly.

For future reference this patch missed the 2.0.4 release that went out yesterday in JJB but we typically try to release every 2 weeks give or take a week. Since January we've been trying to get release momentum up in the JJB project.

If you have patches in the future that you'd like to make it in a release window please join us on IRC in #openstack-jjb @ irc.freenode.net and let us know which patches you'd like priority on. We also have a new jjb specific mailing list now on google groups:

    https://groups.google.com/forum/#!forum/jenkins-job-builder

Considering this project seems to be very tightly dependent on JJB it might be good if we collaborate more closely moving forward? (we could certainly use more eyes on JJB as well)

Cheers,
Thanh

**Comment by ktdreyer** [comment]
That sounds really great Thanh! Thank you!

**Comment by mellena1** [comment]
@zxiiro Thanks a lot, that sounds great!

@ktdreyer Do you want to merge the two open PRs and cut a release? I don't think I have much else to add for now.

**Comment by ktdreyer** [comment]
I've tagged and pushed v1.6.0 including this change. Thank you!

**Pull request merged**
